// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1cxEeLhlXS-rfjxY5MZahRfeOkFA0_i0',
    appId: '1:607914583158:web:9e9254caee0205f476eb57',
    messagingSenderId: '607914583158',
    projectId: 'fir-learning-561c9',
    authDomain: 'fir-learning-561c9.firebaseapp.com',
    storageBucket: 'fir-learning-561c9.firebasestorage.app',
    measurementId: 'G-TSRR163MNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjDzfObcaHLoOQlnCG_s8VvxIECLR9VdY',
    appId: '1:607914583158:android:736ecdd2b014e7d476eb57',
    messagingSenderId: '607914583158',
    projectId: 'fir-learning-561c9',
    storageBucket: 'fir-learning-561c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMrgNrZErrc4mPH9TDNho2nEVLmtR7Qzg',
    appId: '1:607914583158:ios:43f07d142abea60076eb57',
    messagingSenderId: '607914583158',
    projectId: 'fir-learning-561c9',
    storageBucket: 'fir-learning-561c9.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLearning',
  );
}
